In [1]:
import pandas as pd

In [2]:
climate_df = pd.read_csv("../climate_and_population_data.csv")

In [3]:
climate_df.head(10)

,city,month,country,high_temp_F,low_temp_F,mean_temp_F,precipitation_in,humidity_percent,dew_point_F,wind_mph,pressure_Hg,visibility_mi,population,lat,lng
0,Accra,January,Ghana,89.0,75.0,82.0,1.57,75.0,73.0,14.0,29.85,5.0,1782150.0,5.556,-0.1969
1,Accra,February,Ghana,90.0,77.0,84.0,1.79,77.0,75.0,17.0,29.84,6.0,1782150.0,5.556,-0.1969
2,Accra,March,Ghana,91.0,78.0,84.0,2.29,78.0,76.0,17.0,29.83,7.0,1782150.0,5.556,-0.1969
3,Accra,April,Ghana,90.0,78.0,84.0,2.93,78.0,76.0,16.0,29.83,7.0,1782150.0,5.556,-0.1969
4,Accra,May,Ghana,89.0,77.0,83.0,5.11,80.0,75.0,15.0,29.87,8.0,1782150.0,5.556,-0.1969
5,Accra,June,Ghana,85.0,75.0,80.0,6.39,84.0,74.0,15.0,29.93,7.0,1782150.0,5.556,-0.1969
6,Accra,July,Ghana,83.0,75.0,79.0,2.78,84.0,73.0,19.0,29.95,7.0,1782150.0,5.556,-0.1969
7,Accra,August,Ghana,83.0,74.0,78.0,1.83,84.0,72.0,20.0,29.95,7.0,1782150.0,5.556,-0.1969
8,Accra,September,Ghana,85.0,75.0,79.0,2.44,84.0,73.0,19.0,29.92,7.0,1782150.0,5.556,-0.1969
9,Accra,October,Ghana,86.0,75.0,80.0,3.75,83.0,74.0,15.0,29.88,7.0,1782150.0,5.556,-0.1969

In [4]:
climate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860 entries, 0 to 1859
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   city              1860 non-null   object
 1   month             1860 non-null   object
 2   country           1860 non-null   object
 3   high_temp_F       1860 non-null   float64
 4   low_temp_F        1860 non-null   float64
 5   mean_temp_F       1860 non-null   float64
 6   precipitation_in  1860 non-null   float64
 7   humidity_percent  1860 non-null   float64
 8   dew_point_F       1860 non-null   float64
 9   wind_mph          1860 non-null   float64
 10  pressure_Hg       1860 non-null   float64
 11  visibility_mi     1848 non-null   float64
 12  population        1860 non-null   float64
 13  lat               1860 non-null   float64
 14  lng               1860 non-null   float64
dtypes: float64(12), object(3)
memory usage: 218.1+ KB

In [5]:
climate_df.describe()

,high_temp_F,low_temp_F,mean_temp_F,precipitation_in,humidity_percent,dew_point_F,wind_mph,pressure_Hg,visibility_mi,population,lat,lng
count,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1860.000000,1848.000000,1.860000e+03,1860.000000,1860.000000
mean,71.852151,54.637097,63.240860,3.093823,68.133871,50.656989,13.155914,30.291392,8.311688,5.340578e+06,25.931326,-6.666219
std,17.930119,17.187947,17.377622,2.736981,13.218153,16.532251,4.411998,4.138125,3.842209,7.158337e+06,26.012255,82.925144
min,-1.000000,-15.000000,-8.000000,0.000000,10.000000,-12.000000,2.000000,29.440000,1.000000,7.380000e+03,-37.814200,-157.846000
25%,60.750000,42.000000,52.000000,1.397500,63.000000,39.000000,10.000000,29.910000,6.000000,9.949380e+05,14.105800,-79.373300
50%,76.000000,56.000000,66.000000,2.545000,70.000000,52.000000,13.000000,29.990000,8.000000,2.319029e+06,34.114100,3.058600
75%,86.000000,69.000000,77.000000,3.912500,77.000000,64.000000,16.000000,30.060000,10.000000,6.211000e+06,43.240000,47.525000
max,116.000000,89.000000,101.000000,33.050000,90.000000,79.000000,30.000000,104.890000,32.000000,3.910500e+07,64.733300,178.433300

In [6]:
climate_df.groupby('country')['population'].sum().sort_values(ascending=False).head(10)

country
United States    1.282713e+09
India            6.891120e+08
China            5.611679e+08
Japan            4.692600e+08
Brazil           4.523868e+08
Pakistan         4.112155e+08
Indonesia        4.050720e+08
Mexico           2.777616e+08
Korea, South     2.761920e+08
Egypt            2.435520e+08
Name: population, dtype: float64