In [1]:
import pandas as pd

In [2]:
climate_df = pd.read_csv("../climate_and_population_data.csv")

In [3]:
climate_df.head(10)

,month,high_temp_F,low_temp_F,mean_temp_F,precipitation_in,humidity_percent,dew_point_F,wind_mph,pressure_Hg,visibility_mi,city,region,country,population,lat,lng
0,January,89.0,75.0,82.0,1.57,75.0,73.0,14.0,29.85,5.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
1,February,90.0,77.0,84.0,1.79,77.0,75.0,17.0,29.84,6.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
2,March,91.0,78.0,84.0,2.29,78.0,76.0,17.0,29.83,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
3,April,90.0,78.0,84.0,2.93,78.0,76.0,16.0,29.83,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
4,May,89.0,77.0,83.0,5.11,80.0,75.0,15.0,29.87,8.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
5,June,85.0,75.0,80.0,6.39,84.0,74.0,15.0,29.93,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
6,July,83.0,75.0,79.0,2.78,84.0,73.0,19.0,29.95,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
7,August,83.0,74.0,78.0,1.83,84.0,72.0,20.0,29.95,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
8,September,85.0,75.0,79.0,2.44,84.0,73.0,19.0,29.92,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969
9,October,86.0,75.0,80.0,3.75,83.0,74.0,15.0,29.88,7.0,Accra,Greater Accra,Ghana,1782150.0,5.556,-0.1969

In [4]:
climate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1668 entries, 0 to 1667
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             1668 non-null   object
 1   high_temp_F       1668 non-null   float64
 2   low_temp_F        1668 non-null   float64
 3   mean_temp_F       1668 non-null   float64
 4   precipitation_in  1668 non-null   float64
 5   humidity_percent  1668 non-null   float64
 6   dew_point_F       1668 non-null   float64
 7   wind_mph          1668 non-null   float64
 8   pressure_Hg       1668 non-null   float64
 9   visibility_mi     1656 non-null   float64
 10  city              1668 non-null   object
 11  region            1620 non-null   object
 12  country           1668 non-null   object
 13  population        1668 non-null   float64
 14  lat               1668 non-null   float64
 15  lng               1668 non-null   float64
dtypes: float64(12), object(4)
memory usage: 208.6+ KB

In [5]:
climate_df.describe()

,high_temp_F,low_temp_F,mean_temp_F,precipitation_in,humidity_percent,dew_point_F,wind_mph,pressure_Hg,visibility_mi,population,lat,lng
count,1668.000000,1668.000000,1668.000000,1668.000000,1668.000000,1668.000000,1668.000000,1668.000000,1656.000000,1.668000e+03,1668.000000,1668.000000
mean,71.797962,54.628297,63.207434,3.018195,69.060552,51.004197,13.089329,29.963657,8.119565,5.912364e+06,24.700135,3.161191
std,18.082111,17.295858,17.505064,2.785105,12.958632,16.470092,4.576202,0.138248,3.975934,7.318287e+06,27.014075,81.609157
min,-1.000000,-15.000000,-8.000000,0.000000,10.000000,-12.000000,2.000000,29.440000,1.000000,1.322400e+04,-37.814200,-157.846000
25%,61.000000,43.000000,52.000000,1.287500,64.000000,40.000000,10.000000,29.890000,6.000000,1.249597e+06,12.979100,-75.133900
50%,76.000000,56.000000,66.000000,2.360000,71.000000,52.000000,13.000000,29.980000,7.000000,2.748109e+06,32.793500,12.568900
75%,86.000000,69.000000,77.000000,3.852500,78.000000,64.000000,16.000000,30.050000,10.000000,7.171000e+06,44.647500,55.309400
max,116.000000,89.000000,101.000000,33.050000,90.000000,79.000000,30.000000,30.410000,32.000000,3.910500e+07,64.733300,178.433300

In [6]:
climate_df.groupby('country')['population'].sum().sort_values(ascending=False).head(10)

country
United States    1.279614e+09
India            6.891120e+08
China            5.611679e+08
Japan            4.692600e+08
Brazil           4.523868e+08
Pakistan         4.112155e+08
Indonesia        4.050720e+08
Mexico           2.777616e+08
Korea, South     2.761920e+08
Egypt            2.435520e+08
Name: population, dtype: float64